// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';
import type { QueryOperationTypes as PgTargetQueryOps } from '@prisma/orm-postgres/target/operation-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'bc5ff275dc85c9f7b1033387af0c22ec7afc0b7cc679106ce50bcab31c0a83e4'>;
export type ExecutionHash =
  ExecutionHashBase<'e72a6cd7582c8adc342bda056cd4c3721b78724c8250921946d524960379d4b7'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Application: {
      readonly applicantId: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly message: CodecTypes['pg/text@1']['output'] | null;
      readonly publicationId: CodecTypes['pg/text@1']['output'];
      readonly status: 'PENDING' | 'ACCEPTED' | 'REJECTED';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly Message: {
      readonly content: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly publicationId: CodecTypes['pg/text@1']['output'];
      readonly senderId: CodecTypes['pg/text@1']['output'];
    };
    readonly Profile: {
      readonly alias: CodecTypes['pg/text@1']['output'];
      readonly avatarUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly phone: CodecTypes['pg/text@1']['output'] | null;
      readonly position: CodecTypes['pg/text@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly zone: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly Publication: {
      readonly allowsSubs: CodecTypes['pg/bool@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly creatorId: CodecTypes['pg/text@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly locationLat: CodecTypes['pg/float8@1']['output'] | null;
      readonly locationLng: CodecTypes['pg/float8@1']['output'] | null;
      readonly locationName: CodecTypes['pg/text@1']['output'];
      readonly matchDate: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly matchType: 'FUTBOL_5' | 'FUTBOL_7' | 'FUTBOL_8' | 'FUTBOL_11';
      readonly missingSlots: CodecTypes['pg/int4@1']['output'];
      readonly status: 'OPEN' | 'FULL' | 'CANCELLED' | 'COMPLETED';
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly type: 'LOOKING_FOR_PLAYERS' | 'LOOKING_FOR_RIVAL';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Application: {
      readonly applicantId: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly message: CodecTypes['pg/text@1']['input'] | null;
      readonly publicationId: CodecTypes['pg/text@1']['input'];
      readonly status: 'PENDING' | 'ACCEPTED' | 'REJECTED';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly Message: {
      readonly content: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly publicationId: CodecTypes['pg/text@1']['input'];
      readonly senderId: CodecTypes['pg/text@1']['input'];
    };
    readonly Profile: {
      readonly alias: CodecTypes['pg/text@1']['input'];
      readonly avatarUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly phone: CodecTypes['pg/text@1']['input'] | null;
      readonly position: CodecTypes['pg/text@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly zone: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly Publication: {
      readonly allowsSubs: CodecTypes['pg/bool@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly creatorId: CodecTypes['pg/text@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly locationLat: CodecTypes['pg/float8@1']['input'] | null;
      readonly locationLng: CodecTypes['pg/float8@1']['input'] | null;
      readonly locationName: CodecTypes['pg/text@1']['input'];
      readonly matchDate: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly matchType: 'FUTBOL_5' | 'FUTBOL_7' | 'FUTBOL_8' | 'FUTBOL_11';
      readonly missingSlots: CodecTypes['pg/int4@1']['input'];
      readonly status: 'OPEN' | 'FULL' | 'CANCELLED' | 'COMPLETED';
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly type: 'LOOKING_FOR_PLAYERS' | 'LOOKING_FOR_RIVAL';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly applications: {
      readonly applicant_id: CodecTypes['pg/text@1']['output'];
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly message: CodecTypes['pg/text@1']['output'] | null;
      readonly publication_id: CodecTypes['pg/text@1']['output'];
      readonly status: 'PENDING' | 'ACCEPTED' | 'REJECTED';
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly messages: {
      readonly content: CodecTypes['pg/text@1']['output'];
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly publication_id: CodecTypes['pg/text@1']['output'];
      readonly sender_id: CodecTypes['pg/text@1']['output'];
    };
    readonly profiles: {
      readonly alias: CodecTypes['pg/text@1']['output'];
      readonly avatar_url: CodecTypes['pg/text@1']['output'] | null;
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly phone: CodecTypes['pg/text@1']['output'] | null;
      readonly position: CodecTypes['pg/text@1']['output'] | null;
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly zone: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly publications: {
      readonly allows_subs: CodecTypes['pg/bool@1']['output'];
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly creator_id: CodecTypes['pg/text@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly location_lat: CodecTypes['pg/float8@1']['output'] | null;
      readonly location_lng: CodecTypes['pg/float8@1']['output'] | null;
      readonly location_name: CodecTypes['pg/text@1']['output'];
      readonly match_date: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly match_type: 'FUTBOL_5' | 'FUTBOL_7' | 'FUTBOL_8' | 'FUTBOL_11';
      readonly missing_slots: CodecTypes['pg/int4@1']['output'];
      readonly status: 'OPEN' | 'FULL' | 'CANCELLED' | 'COMPLETED';
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly type: 'LOOKING_FOR_PLAYERS' | 'LOOKING_FOR_RIVAL';
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly applications: {
      readonly applicant_id: CodecTypes['pg/text@1']['input'];
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly message: CodecTypes['pg/text@1']['input'] | null;
      readonly publication_id: CodecTypes['pg/text@1']['input'];
      readonly status: 'PENDING' | 'ACCEPTED' | 'REJECTED';
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly messages: {
      readonly content: CodecTypes['pg/text@1']['input'];
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly publication_id: CodecTypes['pg/text@1']['input'];
      readonly sender_id: CodecTypes['pg/text@1']['input'];
    };
    readonly profiles: {
      readonly alias: CodecTypes['pg/text@1']['input'];
      readonly avatar_url: CodecTypes['pg/text@1']['input'] | null;
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly phone: CodecTypes['pg/text@1']['input'] | null;
      readonly position: CodecTypes['pg/text@1']['input'] | null;
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly zone: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly publications: {
      readonly allows_subs: CodecTypes['pg/bool@1']['input'];
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly creator_id: CodecTypes['pg/text@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly location_lat: CodecTypes['pg/float8@1']['input'] | null;
      readonly location_lng: CodecTypes['pg/float8@1']['input'] | null;
      readonly location_name: CodecTypes['pg/text@1']['input'];
      readonly match_date: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly match_type: 'FUTBOL_5' | 'FUTBOL_7' | 'FUTBOL_8' | 'FUTBOL_11';
      readonly missing_slots: CodecTypes['pg/int4@1']['input'];
      readonly status: 'OPEN' | 'FULL' | 'CANCELLED' | 'COMPLETED';
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly type: 'LOOKING_FOR_PLAYERS' | 'LOOKING_FOR_RIVAL';
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Application = {
    applicantId: CodecTypes['pg/text@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    message: CodecTypes['pg/text@1']['output'] | null;
    publicationId: CodecTypes['pg/text@1']['output'];
    status: 'PENDING' | 'ACCEPTED' | 'REJECTED';
    updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    applicant: public_Profile;
    publication: public_Publication;
    readonly [RelationKeys]?: 'applicant' | 'publication';
  };
  export type public_Message = {
    content: CodecTypes['pg/text@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    publicationId: CodecTypes['pg/text@1']['output'];
    senderId: CodecTypes['pg/text@1']['output'];
    publication: public_Publication;
    sender: public_Profile;
    readonly [RelationKeys]?: 'publication' | 'sender';
  };
  export type public_Profile = {
    alias: CodecTypes['pg/text@1']['output'];
    avatarUrl: CodecTypes['pg/text@1']['output'] | null;
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    phone: CodecTypes['pg/text@1']['output'] | null;
    position: CodecTypes['pg/text@1']['output'] | null;
    updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    zone: CodecTypes['pg/text@1']['output'] | null;
    applications: public_Application[];
    messages: public_Message[];
    publications: public_Publication[];
    readonly [RelationKeys]?: 'applications' | 'messages' | 'publications';
  };
  export type public_Publication = {
    allowsSubs: CodecTypes['pg/bool@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    creatorId: CodecTypes['pg/text@1']['output'];
    description: CodecTypes['pg/text@1']['output'] | null;
    id: CodecTypes['pg/text@1']['output'];
    locationLat: CodecTypes['pg/float8@1']['output'] | null;
    locationLng: CodecTypes['pg/float8@1']['output'] | null;
    locationName: CodecTypes['pg/text@1']['output'];
    matchDate: CodecTypes['pg/timestamptz-string@1']['output'];
    matchType: 'FUTBOL_5' | 'FUTBOL_7' | 'FUTBOL_8' | 'FUTBOL_11';
    missingSlots: CodecTypes['pg/int4@1']['output'];
    status: 'OPEN' | 'FULL' | 'CANCELLED' | 'COMPLETED';
    title: CodecTypes['pg/text@1']['output'];
    type: 'LOOKING_FOR_PLAYERS' | 'LOOKING_FOR_RIVAL';
    updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    applications: public_Application[];
    creator: public_Profile;
    messages: public_Message[];
    readonly [RelationKeys]?: 'applications' | 'creator' | 'messages';
  };
}

export declare const models: {
  public: {
    Application: Models.public_Application;
    Message: Models.public_Message;
    Profile: Models.public_Profile;
    Publication: Models.public_Publication;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly applications: {
              columns: {
                readonly applicant_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly message: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly publication_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'PENDING'>;
                  };
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['publication_id', 'applicant_id'] }];
              indexes: readonly [
                {
                  readonly name: 'applications_applicant_id_idx_692f8762';
                  readonly prefix: 'applications_applicant_id_idx';
                  readonly columns: readonly ['applicant_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'applications_publication_id_idx_51db2dd0';
                  readonly prefix: 'applications_publication_id_idx';
                  readonly columns: readonly ['publication_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'applications';
                    readonly columns: readonly ['publication_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'publications';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'applications';
                    readonly columns: readonly ['applicant_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'profiles';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly messages: {
              columns: {
                readonly content: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly publication_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly sender_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'messages_publication_id_idx_51db2dd0';
                  readonly prefix: 'messages_publication_id_idx';
                  readonly columns: readonly ['publication_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'messages_sender_id_idx_311853a4';
                  readonly prefix: 'messages_sender_id_idx';
                  readonly columns: readonly ['sender_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'messages';
                    readonly columns: readonly ['publication_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'publications';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'messages';
                    readonly columns: readonly ['sender_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'profiles';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly profiles: {
              columns: {
                readonly alias: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly avatar_url: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly phone: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly position: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly zone: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['alias'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly publications: {
              columns: {
                readonly allows_subs: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly creator_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly location_lat: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
                readonly location_lng: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
                readonly location_name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly match_date: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly match_type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly missing_slots: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 1>;
                  };
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'OPEN'>;
                  };
                };
                readonly title: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'publications_creator_id_idx_c8bab67a';
                  readonly prefix: 'publications_creator_id_idx';
                  readonly columns: readonly ['creator_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'publications';
                    readonly columns: readonly ['creator_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'profiles';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
          readonly valueSet: {
            readonly ApplicationStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['PENDING', 'ACCEPTED', 'REJECTED'];
            };
            readonly MatchType: {
              readonly kind: 'valueSet';
              readonly values: readonly ['FUTBOL_5', 'FUTBOL_7', 'FUTBOL_8', 'FUTBOL_11'];
            };
            readonly PublicationStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['OPEN', 'FULL', 'CANCELLED', 'COMPLETED'];
            };
            readonly PublicationType: {
              readonly kind: 'valueSet';
              readonly values: readonly ['LOOKING_FOR_PLAYERS', 'LOOKING_FOR_RIVAL'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly applications: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Application';
    };
    readonly messages: { readonly namespace: 'public' & NamespaceId; readonly model: 'Message' };
    readonly profiles: { readonly namespace: 'public' & NamespaceId; readonly model: 'Profile' };
    readonly publications: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Publication';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Application: {
            readonly fields: {
              readonly applicantId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly message: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly publicationId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly applicant: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Profile';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['applicantId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly publication: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Publication';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['publicationId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'applications';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly applicantId: { readonly column: 'applicant_id' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly id: { readonly column: 'id' };
                readonly message: { readonly column: 'message' };
                readonly publicationId: { readonly column: 'publication_id' };
                readonly status: { readonly column: 'status' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
          readonly Message: {
            readonly fields: {
              readonly content: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly publicationId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly senderId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly publication: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Publication';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['publicationId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly sender: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Profile';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['senderId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'messages';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly content: { readonly column: 'content' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly id: { readonly column: 'id' };
                readonly publicationId: { readonly column: 'publication_id' };
                readonly senderId: { readonly column: 'sender_id' };
              };
            };
          };
          readonly Profile: {
            readonly fields: {
              readonly alias: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly avatarUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly phone: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly position: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly zone: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly applications: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Application';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['applicantId'];
                };
              };
              readonly messages: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Message';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['senderId'];
                };
              };
              readonly publications: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Publication';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['creatorId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'profiles';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly alias: { readonly column: 'alias' };
                readonly avatarUrl: { readonly column: 'avatar_url' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly id: { readonly column: 'id' };
                readonly phone: { readonly column: 'phone' };
                readonly position: { readonly column: 'position' };
                readonly updatedAt: { readonly column: 'updated_at' };
                readonly zone: { readonly column: 'zone' };
              };
            };
          };
          readonly Publication: {
            readonly fields: {
              readonly allowsSubs: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly creatorId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly locationLat: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly locationLng: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly locationName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly matchDate: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly matchType: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly missingSlots: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly applications: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Application';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['publicationId'];
                };
              };
              readonly creator: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Profile';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['creatorId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly messages: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Message';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['publicationId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'publications';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly allowsSubs: { readonly column: 'allows_subs' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly creatorId: { readonly column: 'creator_id' };
                readonly description: { readonly column: 'description' };
                readonly id: { readonly column: 'id' };
                readonly locationLat: { readonly column: 'location_lat' };
                readonly locationLng: { readonly column: 'location_lng' };
                readonly locationName: { readonly column: 'location_name' };
                readonly matchDate: { readonly column: 'match_date' };
                readonly matchType: { readonly column: 'match_type' };
                readonly missingSlots: { readonly column: 'missing_slots' };
                readonly status: { readonly column: 'status' };
                readonly title: { readonly column: 'title' };
                readonly type: { readonly column: 'type' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
        };
        readonly enum: {
          readonly ApplicationStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'PENDING'; readonly value: 'PENDING' },
              { readonly name: 'ACCEPTED'; readonly value: 'ACCEPTED' },
              { readonly name: 'REJECTED'; readonly value: 'REJECTED' },
            ];
          };
          readonly MatchType: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'FUTBOL_5'; readonly value: 'FUTBOL_5' },
              { readonly name: 'FUTBOL_7'; readonly value: 'FUTBOL_7' },
              { readonly name: 'FUTBOL_8'; readonly value: 'FUTBOL_8' },
              { readonly name: 'FUTBOL_11'; readonly value: 'FUTBOL_11' },
            ];
          };
          readonly PublicationStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'OPEN'; readonly value: 'OPEN' },
              { readonly name: 'FULL'; readonly value: 'FULL' },
              { readonly name: 'CANCELLED'; readonly value: 'CANCELLED' },
              { readonly name: 'COMPLETED'; readonly value: 'COMPLETED' },
            ];
          };
          readonly PublicationType: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'LOOKING_FOR_PLAYERS'; readonly value: 'LOOKING_FOR_PLAYERS' },
              { readonly name: 'LOOKING_FOR_RIVAL'; readonly value: 'LOOKING_FOR_RIVAL' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'id';
            readonly namespace: 'public';
            readonly table: 'applications';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'id';
            readonly namespace: 'public';
            readonly table: 'messages';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'id';
            readonly namespace: 'public';
            readonly table: 'publications';
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
